### PR TITLE
Use secp256k1_ec_ prefix for non-ECDSA key operations

### PR DESCRIPTION
**Pull request by ph4m**
See API change @ https://github.com/bitcoin/secp256k1/commit/ae6bc76e32016063a591399a7a2d7bac646603bc

### CODE REVIEW

**Comment by metalicjames** [comment]
I'll close and merge it, thanks.

**Comment by ph4m** [comment]
My pleasure. You might need to update your system to the latest version of secp256k1, though.

**Comment by metalicjames** [comment]
What is the highest version of libsecp256k1 this commit can build with? I'll then be able to update the docs.

**Comment by ph4m** [comment]
Well now it is compatible with the latest version of libsecp256k1 (ran a fresh build today), as of November 11th 2014 (latest commit on Nov. 5th).

**Pull request merged**
